// Asset reference layer. Components never hardcode media paths — they ask for a key.
// Every entry marked status: 'placeholder' is a temporary picture of the same subject and format,
// generated by scripts/gen-media.mjs into public/media. Replacing one = replacing the file at that
// path or editing one line here. Real photography swaps in with no component change.

export type AssetStatus = 'placeholder' | 'find' | 'uploaded'

export type Asset = {
  src: string
  alt: string
  width: number
  height: number
  status: AssetStatus
  usage: string
}

export const assets = {
  heroProduct: { src: '/media/hero-product.svg', alt: 'A bottle of Quiet Harbour on a clean surface', width: 1600, height: 2000, status: 'placeholder', usage: 'Home — Product stage' },
  heroStage: { src: '/media/hero-stage.svg', alt: '', width: 2400, height: 1350, status: 'placeholder', usage: 'Home — Product stage backdrop' },

  quietHarbour: { src: '/media/quiet-harbour.svg', alt: 'Quiet Harbour — a bottle on a clean surface', width: 1600, height: 2000, status: 'placeholder', usage: 'Product grid' },
  quietHarbourAlt: { src: '/media/quiet-harbour-alt.svg', alt: '', width: 1600, height: 2000, status: 'placeholder', usage: 'Product grid hover' },
  warmOrchard: { src: '/media/warm-orchard.svg', alt: 'Warm Orchard — a bottle on a clean surface', width: 1600, height: 2000, status: 'placeholder', usage: 'Product grid' },
  warmOrchardAlt: { src: '/media/warm-orchard-alt.svg', alt: '', width: 1600, height: 2000, status: 'placeholder', usage: 'Product grid hover' },
  readingRoom: { src: '/media/reading-room.svg', alt: 'Reading Room — a bottle on a clean surface', width: 1600, height: 2000, status: 'placeholder', usage: 'Product grid' },
  readingRoomAlt: { src: '/media/reading-room-alt.svg', alt: '', width: 1600, height: 2000, status: 'placeholder', usage: 'Product grid hover' },
  firstRain: { src: '/media/first-rain.svg', alt: 'First Rain — a bottle on a clean surface', width: 1600, height: 2000, status: 'placeholder', usage: 'Product grid' },
  firstRainAlt: { src: '/media/first-rain-alt.svg', alt: '', width: 1600, height: 2000, status: 'placeholder', usage: 'Product grid hover' },
  nightGarden: { src: '/media/night-garden.svg', alt: 'Night Garden — a bottle on a clean surface', width: 1600, height: 2000, status: 'placeholder', usage: 'Product grid' },
  nightGardenAlt: { src: '/media/night-garden-alt.svg', alt: '', width: 1600, height: 2000, status: 'placeholder', usage: 'Product grid hover' },

  highlightQuietHarbour: { src: '/media/highlight-quiet-harbour.svg', alt: 'Quiet Harbour shown up close', width: 1600, height: 1600, status: 'placeholder', usage: 'Product Highlight' },
  highlightFirstRain: { src: '/media/highlight-first-rain.svg', alt: 'First Rain shown up close', width: 1600, height: 1600, status: 'placeholder', usage: 'Product Highlight' },

  collection: { src: '/media/collection.svg', alt: 'The Hours collection', width: 1600, height: 2000, status: 'placeholder', usage: 'Collection' },
  editorialPlace: { src: '/media/editorial-place.svg', alt: 'The workshop at first light', width: 2400, height: 1600, status: 'placeholder', usage: 'Editorial Story' },
  editorialDetail: { src: '/media/editorial-detail.svg', alt: 'A still life of bottles and notes', width: 1600, height: 2000, status: 'placeholder', usage: 'Editorial Story' },
  aboutPortrait: { src: '/media/about-portrait.svg', alt: 'Vera, in the workshop', width: 1600, height: 2000, status: 'placeholder', usage: 'About' },
} as const satisfies Record<string, Asset>

export type AssetKey = keyof typeof assets

/** Resolve one asset by key. */
export function getAsset(id: AssetKey): Asset {
  return assets[id]
}