import { chromeNote, validateRecipe } from '@/features/recipes/engine'
import { TYPE_UTILITIES, typeVars } from '@/lib/type-tokens'
import type { AssetManifest, PageSection, UniversalRecipe } from '@/types/domain'

/** Every section in build order: shared navbar, then each page's own sections (tagged with its page label), then shared footer. */
export function flattenPages(r: UniversalRecipe): (PageSection & { page: string | null })[] {
  return [
    { ...r.chrome.navbar, page: null },
    ...r.pages.flatMap((p) => p.sections.map((s) => ({ ...s, page: p.label }))),
    { ...r.chrome.footer, page: null },
  ]
}

export function assertComplete(r: UniversalRecipe) {
  const missing = validateRecipe(r)
  if (missing.length) throw new Error(`Recipe incomplete — missing: ${missing.join(', ')}`)
}

export function assetManifest(r: UniversalRecipe): AssetManifest {
  return Object.fromEntries(r.assetRequirements.map((a) => [a.key, {
    required: a.level === 'required', level: a.level, status: a.status, source: a.source, replaceWith: a.replaceWith, usage: a.usage, specs: a.specs,
    providedFiles: a.providedFiles,
  }]))
}

export const manifestJson = (r: UniversalRecipe) => JSON.stringify({ recipe: r.id, title: r.title, assets: assetManifest(r) }, null, 2) + '\n'

export const extOf = (name: string) => (/\.([a-z0-9]+)$/i.exec(name)?.[1] ?? 'bin').toLowerCase()

/** Where each file the user actually uploaded will land inside the generated project / zip — matches assetsConfigTs. */
export function providedFilePaths(r: UniversalRecipe) {
  return r.assetRequirements
    .filter((a) => a.providedFiles?.length)
    .flatMap((a) => a.providedFiles!.map((f, i) => ({
      key: a.key, fileId: f.fileId, name: f.name,
      webPath: `/media/${a.key}${a.providedFiles!.length > 1 ? `-${i + 1}` : ''}.${extOf(f.name)}`,
    })))
    .map((f) => ({ ...f, zipPath: `public${f.webPath}` }))
}

export function tokensCss(r: UniversalRecipe) {
  const t = r.visualSystem.typography
  const colors = [...r.visualSystem.palette.tokens.map((c) => `  --color-${c.role}: ${c.hex};`), ...(r.visualSystem.rotation?.colors.map((c, i) => `  --color-chapter-${i + 1}: ${c}; /* ${r.visualSystem.rotation!.name} — chapter ${i + 1} */`) ?? [])].join('\n')
  const fonts = (['display', 'heading', 'body', 'utility'] as const).map((k) => `  --font-${k}: '${t[k].family}';`).join('\n')
  const sh = r.visualSystem.shape
  const shape = `  /* Shape: ${sh.name} — ${sh.rule} */\n  --radius-button: ${sh.button};\n  --radius-card: ${sh.card};\n  --radius-media: ${sh.media};\n  --shadow-card: ${sh.shadow};`
  const type = Object.entries(typeVars(t)).filter(([k]) => !k.startsWith('--font-')).map(([k, v]) => `  ${k}: ${v};`).join('\n')
  return `/* ${r.title} — design tokens generated by OpusKit */\n@import "tailwindcss";\n\n@theme {\n${colors}\n${fonts}\n${shape}\n  --spacing: 4px;\n}\n\n:root {\n  color-scheme: ${r.visualSystem.palette.dark ? 'dark' : 'light'}; --border-ui: ${sh.border};\n  /* Type roles — use the type-display / type-heading / type-body / type-utility classes */\n${type}\n}\n\n${TYPE_UTILITIES}\nbody { background: var(--color-background); color: var(--color-text); font-family: var(--font-body), sans-serif; }\n`
}

export function assetsConfigTs(r: UniversalRecipe) {
  const provided = providedFilePaths(r)
  const entries = r.assetRequirements
    .filter((a) => ['images', 'video', 'product-photos', 'illustrations', '3d', 'audio'].includes(a.asset))
    .map((a) => {
      const mine = provided.filter((f) => f.key === a.key).map((f) => f.webPath)
      const fallback = `/media/${a.key}.${a.asset === 'video' ? 'mp4' : a.asset === '3d' ? 'glb' : a.asset === 'audio' ? 'mp3' : 'jpg'}`
      const paths = mine.length ? mine : [fallback]
      const gallery = paths.length > 1 ? `, gallery: ${JSON.stringify(paths)}` : ''
      return `  ${a.key}: { src: ${JSON.stringify(paths[0])}, alt: '', status: '${a.status}', usage: ${JSON.stringify(a.usage)}${gallery} },`
    })
    .join('\n')
  return `// Asset reference layer. Components never hardcode media paths — they ask for a key.\n// Paths under files you uploaded during creation point at the real file, already included in this package.\n// Replacing a placeholder = replacing the file at that path or editing one line here.\nexport const assets = {\n${entries}\n} as const\n\nexport type AssetKey = keyof typeof assets\n`
}

export function visualQa(r: UniversalRecipe): string[] {
  const t = r.visualSystem.typography
  return [
    `Background is ${r.visualSystem.palette.tokens[0].hex}; no other page background colors are introduced.`,
    `Display text uses ${t.display.family} ${t.display.weight}; body uses ${t.body.family}; no other families appear.`,
    r.visualSystem.rotation ? `Colour chapters (${r.visualSystem.rotation.name}): each chapter section owns one accent as a full colour field (--color-chapter-1..3, in turn); never two chapter colours in one view, and text never sits on them without AA contrast.` : `Accent ${r.visualSystem.palette.tokens.find((x) => x.role === 'accent')?.hex} covers < 5% of any viewport.`,
    `Pages: ${r.pages.map((p) => p.label).join(' · ')} — every page shares the same navbar and footer${r.pages.some((p) => p.hide) ? `, except: ${r.pages.filter((p) => p.hide).map((p) => `${p.label} — ${chromeNote(p).toLowerCase()}`).join('; ')} Leave them out with a route group whose own layout.tsx omits them — never render and hide with CSS` : ''}.`,
    `Footer “${r.chrome.footerStyle.name}”: ${r.chrome.footerStyle.composition}`,
    ...r.pages.map((p) => `${p.label} section order: ${p.sections.map((s) => s.name.split(' — ')[0]).join(' → ')}.`),
    `Hero matches "${r.media.hero.name}": ${r.media.hero.composition}`,
    ...r.pages.flatMap((p) => p.sections.filter((s, i) => s.id === 'hero' && i > 0).map(() => `${p.label}: the hero sits mid-page exactly where the section order puts it — a full-width band after the sections above it, not moved to the top; the page's first section carries the h1.`)),
    `Controls and forms use shadcn/ui (${r.implementation.ui.components.map((c) => c.slug).join(', ')}) restyled to the recipe tokens and shape — no unstyled native select, date input or checkbox anywhere; the date field is a Calendar in a Popover.`,
    'Sections with ready code are built from their component in src/components/sections/ (real copy and media through props, no placeholder text left) and styled only through the recipe tokens. Pass the framework link as `link` (Next.js: `link={Link}` from next/link) so in-site links navigate client-side and respect basePath; without it they render plain <a>.',
    ...r.pieces.map((p) => `Kit piece "${p.name}" (<${p.exportName}/> from ${p.path}) is used on ${p.where}, unchanged in behaviour and styled only through the recipe tokens.`),
    ...(r.concept ? [`Big idea “${r.concept.name}” is visible on every page: ${r.concept.motif.charAt(0).toLowerCase()}${r.concept.motif.slice(1)}`, `Chapters open as the big idea says: ${r.concept.chapters}`, `The site ends as the big idea says: ${r.concept.ending}`] : []),
    ...r.signatures.map((s) => `Signature moment "${s.name}" is built on ${s.where}, with its mobile and reduced-motion versions.`),
    'Every page passes the award checklist in the recipe (one idea, one unforgettable moment per page, type scale contrast, motion choreography, mobile as its own composition, a designed ending).',
    ...(r.media.imagery ? [`Photos are shown as "${r.media.imagery.presentation.name}" (${r.media.imagery.presentation.behavior.split(';')[0]})${r.media.imagery.note ? `, and the owner's request is met: “${r.media.imagery.note}”` : ''}.`] : []),
    ...(r.media.framing ? [r.metadata.spec.videoFrame === "original" ? "Owner’s video keeps its own shape on every screen — never cropped wide or stretched." : "Owner’s video fills desktop and tablet screens at 16:9 (no bars, no stretching, no narrow strip); phones play the original shape."] : []),
    ...(r.assetRequirements.some((a) => a.asset === "video") ? ["Video: public/media/heroVideo.mp4 and mobileVideoEncode.mp4 exist and were produced by prepare-video.sh (not raw browser uploads); file size ≤ 6 MB desktop / ≤ 3 MB mobile; poster images (posterImage.jpg, posterMobile.jpg) exist and load before the video.", "Video sharpness: ffprobe shows heroVideo.mp4 ≥ 1920 px wide and mobileVideoEncode.mp4 ≥ 1080 px tall — if not, re-run prepare-video.sh (it sharpens small sources) rather than letting the browser stretch it."] : []),
    ...(r.media.storytelling ? ['Scroll film: forward, fast and backward scrolling move the video with the scroll; every scene message appears on its own scene, one at a time (desktop and 390px).'] : []),
    `Layout: ${r.layoutSystem.columns}; section spacing ${r.layoutSystem.sectionSpacing}.`,
    `Shape “${r.visualSystem.shape.name}”: buttons ${r.visualSystem.shape.button}, cards ${r.visualSystem.shape.card}, media ${r.visualSystem.shape.media} radius (rounded-button / rounded-card / rounded-media) — ${r.visualSystem.shape.rule}`,
    `Menu “${r.chrome.nav.name}”: ${r.chrome.nav.composition}`,
    ...[...r.creativeDirection.avoid, ...r.creativeDirection.genericAvoid].map((a) => `Absent: ${a}.`),
    'Mobile (390px): no horizontal scroll, headlines re-broken intentionally, touch targets ≥ 44px.',
    'prefers-reduced-motion: every animation has its documented alternative.',
    'Every media element is rendered through the asset config layer; temporary assets are listed in the manifest.',
    'Lighthouse on mobile: LCP < 2.5s, CLS < 0.1.',
  ]
}

/** How the coding agent should work: build everything in one pass, stop only when truly blocked. */
export function workingRules(r: UniversalRecipe, plan: string, qa: string): string {
  return `## How to work
- Build the complete site in one pass: every page, section and step in ${plan}, in order. Do not stop between steps to ask for review, confirmation or permission to continue.
- Start by writing a short plan (5–8 lines: visual direction, hero${r.media.storytelling ? ', the scroll-film scene map' : ''}, motion, how desktop and mobile differ), then implement immediately — do not wait for approval.
- After each step, check it against ${qa} yourself and fix what fails before moving on.
- Only stop to ask when truly blocked: a required file is missing and the recipe gives no temporary option, or two recipe rules contradict each other.
- When finished: run the production build, fix every build and runtime error, check desktop (1440px) and mobile (390px) in a real browser, start the dev server and reply with the localhost URL and any temporary assets still to replace.
`
}

export const frontmatter = (fields: Record<string, string | boolean>) =>
  `---\n${Object.entries(fields).map(([k, v]) => `${k}: ${typeof v === 'string' && /[:#"']/.test(v) ? JSON.stringify(v) : v}`).join('\n')}\n---\n\n`
