import { validateRecipe } from '@/features/recipes/engine'
import type { AssetManifest, PageSection, UniversalRecipe } from '@/types/domain'

/** Every section in build order: shared navbar, then each page's own sections (tagged with its page label), then shared footer. */
export function flattenPages(r: UniversalRecipe): (PageSection & { page: string | null })[] {
  return [
    { ...r.chrome.navbar, page: null },
    ...r.pages.flatMap((p) => p.sections.map((s) => ({ ...s, page: p.label }))),
    { ...r.chrome.footer, page: null },
  ]
}

export function assertComplete(r: UniversalRecipe) {
  const missing = validateRecipe(r)
  if (missing.length) throw new Error(`Recipe incomplete — missing: ${missing.join(', ')}`)
}

export function assetManifest(r: UniversalRecipe): AssetManifest {
  return Object.fromEntries(r.assetRequirements.map((a) => [a.key, {
    required: a.level === 'required', level: a.level, status: a.status, source: a.source, replaceWith: a.replaceWith, usage: a.usage, specs: a.specs,
    providedFiles: a.providedFiles,
  }]))
}

export const manifestJson = (r: UniversalRecipe) => JSON.stringify({ recipe: r.id, title: r.title, assets: assetManifest(r) }, null, 2) + '\n'

export const extOf = (name: string) => (/\.([a-z0-9]+)$/i.exec(name)?.[1] ?? 'bin').toLowerCase()

/** Where each file the user actually uploaded will land inside the generated project / zip — matches assetsConfigTs. */
export function providedFilePaths(r: UniversalRecipe) {
  return r.assetRequirements
    .filter((a) => a.providedFiles?.length)
    .flatMap((a) => a.providedFiles!.map((f, i) => ({
      key: a.key, fileId: f.fileId, name: f.name,
      webPath: `/media/${a.key}${a.providedFiles!.length > 1 ? `-${i + 1}` : ''}.${extOf(f.name)}`,
    })))
    .map((f) => ({ ...f, zipPath: `public${f.webPath}` }))
}

export function tokensCss(r: UniversalRecipe) {
  const t = r.visualSystem.typography
  const colors = r.visualSystem.palette.tokens.map((c) => `  --color-${c.role}: ${c.hex};`).join('\n')
  const fonts = (['display', 'heading', 'body', 'utility'] as const).map((k) => `  --font-${k}: '${t[k].family}';`).join('\n')
  return `/* ${r.title} — design tokens generated by OpusKit */\n@import "tailwindcss";\n\n@theme {\n${colors}\n${fonts}\n  --spacing: 4px;\n}\n\n:root { color-scheme: ${r.visualSystem.palette.dark ? 'dark' : 'light'}; }\nbody { background: var(--color-background); color: var(--color-text); font-family: var(--font-body), sans-serif; }\n`
}

export function assetsConfigTs(r: UniversalRecipe) {
  const provided = providedFilePaths(r)
  const entries = r.assetRequirements
    .filter((a) => ['images', 'video', 'product-photos', 'illustrations', '3d'].includes(a.asset))
    .map((a) => {
      const mine = provided.filter((f) => f.key === a.key).map((f) => f.webPath)
      const fallback = `/media/${a.key}.${a.asset === 'video' ? 'mp4' : a.asset === '3d' ? 'glb' : 'jpg'}`
      const paths = mine.length ? mine : [fallback]
      const gallery = paths.length > 1 ? `, gallery: ${JSON.stringify(paths)}` : ''
      return `  ${a.key}: { src: ${JSON.stringify(paths[0])}, alt: '', status: '${a.status}', usage: ${JSON.stringify(a.usage)}${gallery} },`
    })
    .join('\n')
  return `// Asset reference layer. Components never hardcode media paths — they ask for a key.\n// Paths under files you uploaded during creation point at the real file, already included in this package.\n// Replacing a placeholder = replacing the file at that path or editing one line here.\nexport const assets = {\n${entries}\n} as const\n\nexport type AssetKey = keyof typeof assets\n`
}

export function visualQa(r: UniversalRecipe): string[] {
  const t = r.visualSystem.typography
  return [
    `Background is ${r.visualSystem.palette.tokens[0].hex}; no other page background colors are introduced.`,
    `Display text uses ${t.display.family} ${t.display.weight}; body uses ${t.body.family}; no other families appear.`,
    `Accent ${r.visualSystem.palette.tokens.find((x) => x.role === 'accent')?.hex} covers < 5% of any viewport.`,
    `Pages: ${r.pages.map((p) => p.label).join(' · ')} — every page shares the same navbar and footer.`,
    ...r.pages.map((p) => `${p.label} section order: ${p.sections.map((s) => s.name.split(' — ')[0]).join(' → ')}.`),
    `Hero matches "${r.media.hero.name}": ${r.media.hero.composition}`,
    `Layout: ${r.layoutSystem.columns}; section spacing ${r.layoutSystem.sectionSpacing}.`,
    ...[...r.creativeDirection.avoid, ...r.creativeDirection.genericAvoid].map((a) => `Absent: ${a}.`),
    'Mobile (390px): no horizontal scroll, headlines re-broken intentionally, touch targets ≥ 44px.',
    'prefers-reduced-motion: every animation has its documented alternative.',
    'Every media element is rendered through the asset config layer; temporary assets are listed in the manifest.',
    'Lighthouse on mobile: LCP < 2.5s, CLS < 0.1.',
  ]
}

export const frontmatter = (fields: Record<string, string | boolean>) =>
  `---\n${Object.entries(fields).map(([k, v]) => `${k}: ${typeof v === 'string' && /[:#"']/.test(v) ? JSON.stringify(v) : v}`).join('\n')}\n---\n\n`
