// Bundles src/pieces/*.tsx as strings, so Build Packages (made in the browser) can ship the exact code OpusKit type-checks.
// Run `npm run pieces` after editing a piece; `npm run check` fails if this file is stale.
import { readFileSync, writeFileSync } from 'node:fs'
import { blocks, heroBlocks } from '../src/data/blocks'
import { pieces } from '../src/data/pieces'

// Bundles ready pieces (src/pieces/) and ready sections (src/sections/) — the exact code OpusKit type-checks.
const read = (dir: string, file: string) => JSON.stringify(readFileSync(new URL(`../src/${dir}/${file}`, import.meta.url), 'utf8'))
export function piecesSource() {
  const pc = Object.values(pieces).map((p) => `  ${JSON.stringify(p.id)}: ${read('pieces', p.file)},`).join('\n')
  const bl = Object.entries(blocks).map(([id, b]) => `  ${JSON.stringify(id)}: ${read('sections', b.file)},`).join('\n')
  const hb = Object.entries(heroBlocks).map(([id, b]) => `  ${JSON.stringify(id)}: ${read('sections', b!.file)},`).join('\n')
  return `// Generated by scripts/pieces-source.ts from src/pieces/ and src/sections/ — do not edit by hand.\nimport type { HeroId, PieceId, SectionId } from '@/types/domain'\n\nexport const pieceSource: Record<PieceId, string> = {\n${pc}\n}\n\nexport const blockSource: Partial<Record<SectionId, string>> = {\n${bl}\n}\n\nexport const heroSource: Partial<Record<HeroId, string>> = {\n${hb}\n}\n`
}

export const GENERATED = new URL('../src/data/pieces-source.generated.ts', import.meta.url)
if (process.argv[1]?.endsWith('pieces-source.ts')) { writeFileSync(GENERATED, piecesSource()); console.log('✓ pieces-source.generated.ts') }
